[WALL]
shape = "conformal"
cw = 0
equal_arc_wall = true
bw = 1.5
dw = 0.5
aw = 0.05
tw = 0.05
a = 0.2415

[Equilibrium]
use_classic_splines = false
mpsi = 128
mtheta = 256
eq_filename = "sol.toml"
psilow = 0.0001
power_b = 0
gse_flag = false
input_only = false
power_r = 0
psihigh = 0.99999
out_2d = false
out_eq_2d = false
out_eq_1d = false
eq_type = "sol"
jac_type = "pest"
bin_eq_2d = true
dump_flag = false
etol = 1.0e-7
bin_2d = false
power_bp = 0
grid_type = "ldp"
newq0 = 0
bin_eq_1d = false

[ForceFreeStates]
force_wv_symmetry = true
con_flag = false
mat_flag = true
passing_flag = true
qhigh = 1000.0
delta_mlow = 8
sing_start = 0
electron_flag = false
thmax0 = 1
kinfac1 = 1.0
ode_flag = true
ktc = 0.1
mthvac = 960
ktanh_flag = true
ion_flag = true
kingridtype = 0
delta_mhigh = 8
singfac_min = 0.0001
bal_flag = false
vac_flag = true
dmlim = 0.2
kin_flag = false
kinfac2 = 1.0
set_psilim_via_dmlim = false
delta_mband = 0
tol_nr = 1.0e-6
nn_low = 1
tol_r = 1.0e-7
crossover = 0.01
ucrit = 1000.0
qlow = 1.02
mer_flag = true
nn_high = 1
ktw = 50.0
