[Wall]
shape = "nowall"
cw = 0
equal_arc_wall = true
bw = 1.5
dw = 0.5
aw = 0.05
tw = 0.05
a = 0.2415

[Equilibrium]
mpsi = 0
psi_accuracy = 0.001
eq_filename = "TkMkr_D3Dlike_Hmode.geqdsk"
psilow = 0.0001
mtheta = 256
power_b = 0
power_r = 0
force_termination = false
psihigh = 0.993
eq_type = "efit"
jac_type = "hamada"
etol = 1.0e-7
power_bp = 0
grid_type = "log_asymptotic"
newq0 = 0

[ForceFreeStates]
con_flag = false
mat_flag = true
passing_flag = true
save_interval = 3
eulerlagrange_tolerance = 1.0e-7
qhigh = 1000.0
delta_mlow = 8
sing_start = 0
electron_flag = false
thmax0 = 1
kinfac1 = 1.0
ode_flag = true
ktc = 0.1
mthvac = 512
ktanh_flag = true
ion_flag = true
kingridtype = 0
delta_mhigh = 8
singfac_min = 0.0001
bal_flag = false
vac_flag = true
dmlim = 0.2
psiedge = 1.0
kin_flag = false
set_psilim_via_dmlim = true
delta_mband = 0
kinfac2 = 1.0
nn_low = 1
ucrit = 10000.0
qlow = 1.02
mer_flag = true
use_parallel = false
use_riccati = true
nn_high = 1
ktw = 50.0

[ForcingTerms]
forcing_data_file = "forcing.dat"
forcing_data_format = "ascii"

[PerturbedEquilibrium]
fixed_boundary = false
output_eigenmodes = true
compute_response = true
verbose = true
compute_singular_coupling = true
write_outputs_to_HDF5 = true
